#+TITLE:yankpad.el [[http://melpa.org/#/yankpad][file:http://melpa.org/packages/yankpad-badge.svg]]

Let's say that you have text snippets that you want to paste, but that [[http://capitaomorte.github.io/yasnippet/][yasnippet]]
or [[https://www.emacswiki.org/emacs/SkeletonMode][skeleton]] is a bit too much when you do not need a shortcut/abbrev for your
snippet. You like org-mode, so why not write your snippets there? Introducing
the yankpad:

#+BEGIN_SRC org
  ,* Category 1

  ,** Snippet title

      Here's a text snippet I want to insert.

  ,** Snippet with keybinding                               :last:tag:is:key:o:

      And here's another snippet. This snippet has tags, and the last of these
      tags should be a key. This will bind the snippet to the key (in this case
      "o") in a prefix map called yankpad-map.

  ,* Category 2

  ,** Explaining categories

      This snippet belongs to another category. Categories are useful if you need
      several yankpads, for instance if you're a teacher (like me) working with
      different courses.

  ,** yasnippet magic

      If you have yasnippet installed (not a requirement), the content in each snippet
      is actually executed by yasnippet! This means that you could run elisp
      inside your snippets: `(+ 3 4)` and have handy tab stop fields.

      | Student | Grade |
      |---------+-------|
      | $1      | $2    |

      That's pretty handy!
      $0

  ,* org-mode

  ,** Major-mode categories

      If you have a category with the same name as a major-mode, that category will be
      activated when switching major-mode. This only affects the local buffer and does
      not modify the global category.

  ,* my-projectile-project

  ,** Projectile based categories

      If you have projectile installed (not a requirement) you can give a category the
      same name as one of your projectile projects. That category will be activated
      when using projectile-find-file on a file in the project.
#+END_SRC

* Setup

1. Install =yankpad= from Melpa, or download =yankpad.el= and add it to your load-path and require it.
2. The default location for the yankpad file is =yankpad.org= in your =org-directory=. This can be changed by modifying the =yankpad-file= variable.
3. Optionally bind =yankpad-map= to a key.
4. That's it!

If you want different heading levels for the categories (default 1) or snippets (default 2), change the value of =yankpad-category-heading-level= and/or =yankpad-snippet-heading-level=.

Here's an example setup using the excellent [[https://github.com/jwiegley/use-package][use-package]]:

#+BEGIN_SRC emacs-lisp
  (use-package yankpad
    :ensure t
    :defer 10
    :init
    (setq yankpad-file "~/yankpad.org")
    :config
    (bind-key "<f7>" 'yankpad-map))
#+END_SRC

* Usage

1. Add entries to your =yankpad-file=. Level 1 headings are categories and level 2 headings are snippets.
2. Insert a snippet with =M-x yankpad-insert=.
3. If you want to change category, use =M-x yankpad-set-category=. If you have a category with the same name as a major-mode (for instance =org-mode=), that category will be locally set when switching major-mode. In the same manner you can name a category to one of your Projectile project names (if Projectile is installed). If there's a clash between major-mode and Projectile categories, Projectile will take precedence.
4. To quickly open your =yankpad-file= for editing, run =M-x yankpad-edit=.

Since a =*= at the beginning of a line would specify a new heading, lines can not begin with =*=. However, you can write =\*= at the beginning of a line, which will be replaced by a =*= when expanding the snippet.

Sometimes it may be useful to set the category automatically for a specific file. In this case you can add =yankpad-category= as a [[https://www.gnu.org/software/emacs/manual/html_node/emacs/Specifying-File-Variables.html][file variable]], for instance by adding this line at the top of your file:

#+BEGIN_SRC
-*- yankpad-category: "Category name"; -*-
#+END_SRC

The above will not add keybindings to =yankpad-map=. In order to do that on a file-to-file basis, add the following to the top of the file instead:

#+BEGIN_SRC
-*- eval: (yankpad-set-local-category "Category name") -*-
#+END_SRC

* Changelog

- 1.10 (May 2016) :: Snippets can have keybindings by tagging them. The last tag will be interpreted as a key and inserted into =yankpad-map=.
